services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  frontend:
    build: .
    command: ["make", "frontend"]
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017

  consumer:
    build: .
    command: ["make", "run-consumer"]
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
