services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db

  frontend:
    build: .
    command: [ "make", "frontend" ]
    ports:
      - "8501:8501"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017

  consumer:
    build: .
    command: [ "make", "run-consumer" ]
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017

volumes:
  mongo-db: { }
